tag_con = {
    "African": "recipes/world/african",
    "Asian": "recipes/world/asian",
    "BBQ": "recipes/bbq",
    "Baking": "recipes/baking",
    "Air Fryer": "recipes/baking/airfryer",
    "Flatbread": "recipes/baking/flatbread",
    "Loaves": "recipes/baking/loaves",
    "Tray Bakes": "recipes/baking/traybakes",
    "Beauty": "recipes/beauty",
    "Breakfast": "recipes/breakfast",
    "Cast Iron": "recipes/castiron",
    "Charcuterie": "recipes/charcuterie",
    "Chinese": "recipes/world/asian/chinese",
    "Classic": "recipes/classic",
    "Dairy": "recipes/dairy",
    "Dessert": "recipes/dessert",
    "Dinner": "recipes/dinner",
    "Drink": "recipes/drink",
    "Dumplings": "recipes/dumplings",
    "Egg Whites": "recipes/leftovers/eggwhites",
    "Eggs": "recipes/eggs",
    "European": "recipes/world/european",
    "Ferments": "recipes/fermentation",
    "Fish": "recipes/fish",
    "Foraging": "recipes/foraging",
    "French": "recipes/world/european/french",
    "Hiking": "recipes/hiking",
    "Hungarian": "recipes/world/european/hungarian",
    "Indian": "recipes/world/asian/indian",
    "Italian": "recipes/world/european/italian",
    "Japanese": "recipes/world/asian/japanese",
    "Korean": "recipes/world/asian/korean",
    "Leftovers": "recipes/leftovers",
    "Malay/Indonesian": "recipes/world/asian/indomalay",
    "Mashed Potatoes": "recipes/leftovers/mashedpotatoes",
    "Meat": "recipes/meat",
    "Mexican": "recipes/world/southamerica/mexican",
    "Middle East": "recipes/world/middleeast",
    "Noodles": "recipes/noodles",
    "Oils": "recipes/sauces/oils",
    "Pasta": "recipes/pasta",
    "Pickle Juice": "recipes/leftovers/picklejuice",
    "Pizza": "recipes/pizza",
    "Polish": "recipes/world/european/polish",
    "Potatoes": "recipes/potatoes",
    "Preserves": "recipes/preserves",
    "Pressure Cooker": "recipes/pressurecooker ",
    "Ramen": "recipes/soup/ramen",
    "Rice": "recipes/rice",
    "Salad": "recipes/salad",
    "Salvador": "recipes/world/southamerica/salvador",
    "Sauces": "recipes/sauces",
    "Sausages": "recipes/meat/sausages",
    "Scandinavian": "recipes/world/european/scandinavian",
    "Side": "recipes/side",
    "Snacks": "recipes/snacks",
    "Soup": "recipes/soup",
    "Sourdough": "recipes/leftovers/sourdough",
    "Sous Vide": "recipes/sousvide",
    "South America": "recipes/world/southamerica",
    "Soy Lees": "recipes/leftovers/soylees",
    "Spanish": "recipes/world/european/spanish",
    "Spent Grain": "recipes/leftovers/spentgrain",
    "Taiwan": "recipes/world/asian/taiwan",
    "Thai": "recipes/world/asian/thai",
    "Tofu": "recipes/tofu",
    "ToDo": "recipes/todo",
    "Classic": "recipes/classic",
    "Cooked": "recipes/cooked",
    "USA": "recipes/world/usa",
    "Vegetarian": "recipes/vegetarian",
    "Vietnamese": "recipes/world/asian/vietnamese",
    "Whey": "recipes/leftovers/whey",
    "World": "recipes/world",
    "Adam Liaw": "recipes/authors/adamliaw",
    "Alton Brown": "recipes/authors/altonbrown",
    "ATK": "recipes/authors/atk",
    "Claudia Roden": "recipes/authors/claudiaroden",
    "David Chang": "recipes/authors/davidchang",
    "Deborah Madison": "recipes/authors/deborahmadison",
    "Elizabeth David": "recipes/authors/elizabethdavid",
    "Food52": "recipes/authors/food52",
    "Fuschia Dunlop": "recipes/authors/fuschiadunlop",
    "Hugh Fearnley-Whittingstall": "recipes/authors/hughfearnley",
    "J Kenji Lopez-Alt": "recipes/authors/kenji",
    "Julia Child": "recipes/authors/juliachild",
    "Maangchi": "recipes/authors/maangchi",
    "Marcella Hazan": "recipes/authors/marcellahazan",
    "Mary Berry": "recipes/authors/maryberry",
    "Nigel Slater": "recipes/authors/nigelslater",
    "Nigella Lawson": "recipes/authors/nigellalawson",
    "Ramen_Lord": "recipes/authors/ramenlord",
    "Samin Nosrat": "recipes/authors/saminnosrat",
    "Steve Raichlen": "recipes/authors/steveraichlen",
    "Yotam Ottolenghi": "recipes/authors/yotamottolenghi"
}